// <auto-generated />
using System;
using Argus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Argus.Data.Migrations
{
    [DbContext(typeof(ArgusDbContext))]
    [Migration("20260401114532_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Argus.Entities.DetectedSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsFalsePositive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("MaskedValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Confidence");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("RuleId");

                    b.HasIndex("ScanRunId");

                    b.HasIndex("Severity");

                    b.HasIndex("Type");

                    b.HasIndex("FilePath", "LineNumber")
                        .IsUnique();

                    b.HasIndex("IsReviewed", "IsFalsePositive");

                    b.HasIndex("ScanRunId", "IsFalsePositive");

                    b.HasIndex("ScanRunId", "Severity")
                        .IsDescending(false, true);

                    b.ToTable("DetectedSecrets");
                });

            modelBuilder.Entity("Argus.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastScanDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Argus.Entities.ScanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComponentCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FilesScanned")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SecretCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("ProjectId", "Status")
                        .IsDescending(false, true);

                    b.ToTable("ScanRuns");
                });

            modelBuilder.Entity("Argus.Entities.SoftwareComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasKnownVulnerabilities")
                        .HasColumnType("bit");

                    b.Property<string>("Homepage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTransitive")
                        .HasColumnType("bit");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PackageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ParentComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublisherUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("HasKnownVulnerabilities");

                    b.HasIndex("IsTransitive");

                    b.HasIndex("PackageUrl")
                        .IsUnique();

                    b.HasIndex("ParentComponentId");

                    b.HasIndex("ScanRunId");

                    b.HasIndex("Type");

                    b.HasIndex("Name", "Version");

                    b.HasIndex("ScanRunId", "HasKnownVulnerabilities");

                    b.HasIndex("ScanRunId", "IsTransitive");

                    b.ToTable("SoftwareComponents");
                });

            modelBuilder.Entity("Argus.Entities.Vulnerability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CveId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CvssScore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvssVector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<Guid>("SoftwareComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CveId")
                        .IsUnique();

                    b.HasIndex("Severity");

                    b.HasIndex("SoftwareComponentId");

                    b.HasIndex("SoftwareComponentId", "Severity");

                    b.ToTable("Vulnerabilities");
                });

            modelBuilder.Entity("Argus.Entities.DetectedSecret", b =>
                {
                    b.HasOne("Argus.Entities.ScanRun", "ScanRun")
                        .WithMany("Secrets")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("Argus.Entities.ScanRun", b =>
                {
                    b.HasOne("Argus.Entities.Project", "Project")
                        .WithMany("ScanRuns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Argus.Entities.SoftwareComponent", b =>
                {
                    b.HasOne("Argus.Entities.SoftwareComponent", "ParentComponent")
                        .WithMany("ChildComponents")
                        .HasForeignKey("ParentComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Argus.Entities.ScanRun", "ScanRun")
                        .WithMany("Components")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComponent");

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("Argus.Entities.Vulnerability", b =>
                {
                    b.HasOne("Argus.Entities.SoftwareComponent", "SoftwareComponent")
                        .WithMany("Vulnerabilities")
                        .HasForeignKey("SoftwareComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoftwareComponent");
                });

            modelBuilder.Entity("Argus.Entities.Project", b =>
                {
                    b.Navigation("ScanRuns");
                });

            modelBuilder.Entity("Argus.Entities.ScanRun", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Secrets");
                });

            modelBuilder.Entity("Argus.Entities.SoftwareComponent", b =>
                {
                    b.Navigation("ChildComponents");

                    b.Navigation("Vulnerabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
